version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.8
    steps:
      - checkout
      - run:
          name: install
          command: yarn --frozen-lockfile --network-concurrency 1
      - run:
          name: test
          command: yarn test
